<a href="https://colab.research.google.com/github/ddhage/ddhage/blob/main/MarathiSentiAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import nltk
import pandas as pd
import numpy as np
import csv
from nltk.tokenize import word_tokenize
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("valid.csv")
txt = ""
with open('valid.csv') as file_obj:
  reader = csv.reader(file_obj)
  for row in reader:
    for words in row:
      txt = txt + words + " "
print(txt)

Saving valid.csv to valid.csv
headline label पहाटे 3:30 वाजता बीग बींनी गायल 'हे' रॅप साँग entertainment राष्ट्रपती आणि पंतप्रधानांनी वाहिली श्रीदेवींना श्रद्धांजली entertainment सायरा बानोंना जागेसाठी धमकावणाऱ्या बिल्डराविरोधात गुन्हा दाखल entertainment मुंबईत पहिल्यांदाच पन्नाशी पार, राज्यात सरासरी 55 टक्के मतदान state अण्णांची मनधरणी करण्यासाठी गिरीश महाजन राळेगणसिद्धीत ! state समीर भुजबळांच्या जामीन अर्जाच्या सुनावणीकडे राज्याचं लक्ष state पुणे मेट्रोचे अडथळे दूर, लवकरच कामाचा श्रीगणेशा ! state राष्ट्रवादी-काँग्रेस नेत्यांमध्ये जुंपली state एकरकमी एफआरपी द्या, नाहीतर संघर्ष अटळ -राजू शेट्टी state आमचा कित्ता गिरवू नका,  पवारांनी टोचले साहित्यिकांचे कान state प्रियांका-निकच्या लग्नाचा पहिला फोटो काढण्यासाठी मॅगझिन्सची चढाओढ entertainment राज ठाकरे हे विचारवंत नेते, शरद पवारांनी उडवली खिल्ली state विदर्भ, मराठवाडय़ात गारपीटीसह अवकाळी पाऊस,अनेक जिल्ह्यात पाण्याची टंचाई state धन्यवाद सर्वांचे..! entertainment सयाजी शिंदेंनी लावलेली झाडं अज्ञातांनी तोडली state चिक्कीनंतर आता बिस्कीट खरे

In [3]:
nltk.download('punkt')
txt = word_tokenize(txt)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [4]:
print(txt)
nltk.download('words')
words = set(nltk.corpus.words.words())
sent = " ".join(w for w in txt if not w.isalpha())
txt2 = word_tokenize(sent)
print(txt2)

['headline', 'label', 'पहाटे', '3:30', 'वाजता', 'बीग', 'बींनी', 'गायल', "'", 'हे', "'", 'रॅप', 'साँग', 'entertainment', 'राष्ट्रपती', 'आणि', 'पंतप्रधानांनी', 'वाहिली', 'श्रीदेवींना', 'श्रद्धांजली', 'entertainment', 'सायरा', 'बानोंना', 'जागेसाठी', 'धमकावणाऱ्या', 'बिल्डराविरोधात', 'गुन्हा', 'दाखल', 'entertainment', 'मुंबईत', 'पहिल्यांदाच', 'पन्नाशी', 'पार', ',', 'राज्यात', 'सरासरी', '55', 'टक्के', 'मतदान', 'state', 'अण्णांची', 'मनधरणी', 'करण्यासाठी', 'गिरीश', 'महाजन', 'राळेगणसिद्धीत', '!', 'state', 'समीर', 'भुजबळांच्या', 'जामीन', 'अर्जाच्या', 'सुनावणीकडे', 'राज्याचं', 'लक्ष', 'state', 'पुणे', 'मेट्रोचे', 'अडथळे', 'दूर', ',', 'लवकरच', 'कामाचा', 'श्रीगणेशा', '!', 'state', 'राष्ट्रवादी-काँग्रेस', 'नेत्यांमध्ये', 'जुंपली', 'state', 'एकरकमी', 'एफआरपी', 'द्या', ',', 'नाहीतर', 'संघर्ष', 'अटळ', '-राजू', 'शेट्टी', 'state', 'आमचा', 'कित्ता', 'गिरवू', 'नका', ',', 'पवारांनी', 'टोचले', 'साहित्यिकांचे', 'कान', 'state', 'प्रियांका-निकच्या', 'लग्नाचा', 'पहिला', 'फोटो', 'काढण्यासाठी', 'मॅगझिन्सची', 'चढाओ

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


['पहाटे', '3:30', 'वाजता', 'बीग', 'बींनी', 'गायल', "'", 'हे', "'", 'रॅप', 'साँग', 'राष्ट्रपती', 'आणि', 'पंतप्रधानांनी', 'वाहिली', 'श्रीदेवींना', 'श्रद्धांजली', 'सायरा', 'बानोंना', 'जागेसाठी', 'धमकावणाऱ्या', 'बिल्डराविरोधात', 'गुन्हा', 'दाखल', 'मुंबईत', 'पहिल्यांदाच', 'पन्नाशी', 'पार', ',', 'राज्यात', 'सरासरी', '55', 'टक्के', 'मतदान', 'अण्णांची', 'मनधरणी', 'करण्यासाठी', 'गिरीश', 'महाजन', 'राळेगणसिद्धीत', '!', 'समीर', 'भुजबळांच्या', 'जामीन', 'अर्जाच्या', 'सुनावणीकडे', 'राज्याचं', 'लक्ष', 'पुणे', 'मेट्रोचे', 'अडथळे', 'दूर', ',', 'कामाचा', 'श्रीगणेशा', '!', 'राष्ट्रवादी-काँग्रेस', 'नेत्यांमध्ये', 'जुंपली', 'एकरकमी', 'एफआरपी', 'द्या', ',', 'नाहीतर', 'संघर्ष', '-राजू', 'शेट्टी', 'आमचा', 'कित्ता', 'गिरवू', 'नका', ',', 'पवारांनी', 'टोचले', 'साहित्यिकांचे', 'कान', 'प्रियांका-निकच्या', 'लग्नाचा', 'पहिला', 'फोटो', 'काढण्यासाठी', 'मॅगझिन्सची', 'चढाओढ', 'राज', 'ठाकरे', 'हे', 'विचारवंत', 'नेते', ',', 'पवारांनी', 'उडवली', 'खिल्ली', 'विदर्भ', ',', 'मराठवाडय़ात', 'गारपीटीसह', 'अवकाळी', 'पाऊस', ',', 'अन

In [5]:
from string import digits

def remove(list):
    remove_digits = str.maketrans('', '', digits)
    list = [i.translate(remove_digits) for i in list]
    return list
txt2 = remove(txt2)
print(txt2)

def remove_punc(string):
    punc = '''!()-[]{};:'"\, <>./?@#$%^&*_~'''
    for ele in string:  
        if ele in punc:  
            string = string.replace(ele, "") 
    return string
 
lst2 = [remove_punc(i) for i in txt2]
print(lst2)

res = []
for ele in lst2:
    if ele.strip():
        res.append(ele)
print(res)

['पहाटे', ':', 'वाजता', 'बीग', 'बींनी', 'गायल', "'", 'हे', "'", 'रॅप', 'साँग', 'राष्ट्रपती', 'आणि', 'पंतप्रधानांनी', 'वाहिली', 'श्रीदेवींना', 'श्रद्धांजली', 'सायरा', 'बानोंना', 'जागेसाठी', 'धमकावणाऱ्या', 'बिल्डराविरोधात', 'गुन्हा', 'दाखल', 'मुंबईत', 'पहिल्यांदाच', 'पन्नाशी', 'पार', ',', 'राज्यात', 'सरासरी', '', 'टक्के', 'मतदान', 'अण्णांची', 'मनधरणी', 'करण्यासाठी', 'गिरीश', 'महाजन', 'राळेगणसिद्धीत', '!', 'समीर', 'भुजबळांच्या', 'जामीन', 'अर्जाच्या', 'सुनावणीकडे', 'राज्याचं', 'लक्ष', 'पुणे', 'मेट्रोचे', 'अडथळे', 'दूर', ',', 'कामाचा', 'श्रीगणेशा', '!', 'राष्ट्रवादी-काँग्रेस', 'नेत्यांमध्ये', 'जुंपली', 'एकरकमी', 'एफआरपी', 'द्या', ',', 'नाहीतर', 'संघर्ष', '-राजू', 'शेट्टी', 'आमचा', 'कित्ता', 'गिरवू', 'नका', ',', 'पवारांनी', 'टोचले', 'साहित्यिकांचे', 'कान', 'प्रियांका-निकच्या', 'लग्नाचा', 'पहिला', 'फोटो', 'काढण्यासाठी', 'मॅगझिन्सची', 'चढाओढ', 'राज', 'ठाकरे', 'हे', 'विचारवंत', 'नेते', ',', 'पवारांनी', 'उडवली', 'खिल्ली', 'विदर्भ', ',', 'मराठवाडय़ात', 'गारपीटीसह', 'अवकाळी', 'पाऊस', ',', 'अनेक', 

In [6]:
str = ""
stlist = ['आहे', 'आणि', 'या', 'व', 'नाही', 'आहेत', 'यानी', 'हे', 'तर', 'ते ', 'असे', 'होते', 'केली', 'हा ', 'ही ', 'पण', 'करणयात', 'काही', 'केले', 'एक', 'केला', 'अशी', 'मात्र  ', 'त्यानी ', 'सुरू', 'करून ', 'होती', 'असून', 'आले', 'त्यामुळे', 'झाली', 'होता', 'दोन', 'झाले', 'मुबी ', 'होत', 'त्या', 'आता', 'असा', 'याच्या', 'त्याच्या', 'ता', 'आली', 'की', 'पम', 'तो', 'झाला', 'त्री', 'तरी', 'म्हणून', 'त्याना', 'अनेक', 'काम', 'माहिती', 'हजार', 'सागित्ले', 'दिली', 'आला', 'आज', 'ती ', 'तसेच', 'एका', 'याची', 'येथील', 'सर्व', 'न', 'डॉ', 'तीन ', 'येथे', 'पाटील', 'असलयाचे', 'त्याची', 'काय', 'आपल्या', 'म्हणजे', 'याना', 'म्हणाले', 'त्याचा', 'असलेल्या', 'मी', 'गेल्या', 'याचा', 'येत', 'म', 'लाख ', 'कमी', 'जात', 'टा', 'होणार', 'किवा', 'का', 'अधिक', 'घेऊन', 'परयतन', 'कोटी', 'झालेल्या', 'निर्ण्य', 'येणार', 'व्यकत']
res2 = []
print(str)
for sub in res:
  if sub in stlist:
    res.remove(sub)
print(res)



['पहाटे', 'वाजता', 'बीग', 'बींनी', 'गायल', 'रॅप', 'साँग', 'राष्ट्रपती', 'पंतप्रधानांनी', 'वाहिली', 'श्रीदेवींना', 'श्रद्धांजली', 'सायरा', 'बानोंना', 'जागेसाठी', 'धमकावणाऱ्या', 'बिल्डराविरोधात', 'गुन्हा', 'दाखल', 'मुंबईत', 'पहिल्यांदाच', 'पन्नाशी', 'पार', 'राज्यात', 'सरासरी', 'टक्के', 'मतदान', 'अण्णांची', 'मनधरणी', 'करण्यासाठी', 'गिरीश', 'महाजन', 'राळेगणसिद्धीत', 'समीर', 'भुजबळांच्या', 'जामीन', 'अर्जाच्या', 'सुनावणीकडे', 'राज्याचं', 'लक्ष', 'पुणे', 'मेट्रोचे', 'अडथळे', 'दूर', 'कामाचा', 'श्रीगणेशा', 'राष्ट्रवादीकाँग्रेस', 'नेत्यांमध्ये', 'जुंपली', 'एकरकमी', 'एफआरपी', 'द्या', 'नाहीतर', 'संघर्ष', 'राजू', 'शेट्टी', 'आमचा', 'कित्ता', 'गिरवू', 'नका', 'पवारांनी', 'टोचले', 'साहित्यिकांचे', 'कान', 'प्रियांकानिकच्या', 'लग्नाचा', 'पहिला', 'फोटो', 'काढण्यासाठी', 'मॅगझिन्सची', 'चढाओढ', 'राज', 'ठाकरे', 'विचारवंत', 'नेते', 'पवारांनी', 'उडवली', 'खिल्ली', 'विदर्भ', 'मराठवाडय़ात', 'गारपीटीसह', 'अवकाळी', 'पाऊस', 'जिल्ह्यात', 'पाण्याची', 'टंचाई', 'धन्यवाद', 'सर्वांचे', 'सयाजी', 'शिंदेंनी', 'लावलेली', 'झाड

In [10]:

#df2 = pd.read_csv("alphabets.csv")
#alphab = []
#with open('alphabets.csv') as file_obj2:
 # reader = csv.reader(file_obj2)
  #for row in reader:
   # for words in row:
    #  alphab.append(words)
#print(alphab)
#nltk.download('words')
#words = set(nltk.corpus.words.words())
#sente = " ".join(w for w in alphab if not w.isalpha())
#result = word_tokenize(sente)
#print(result)
#sente2 = " ".join(w for w in result if not w.isalpha())
#result2 = word_tokenize(sente2)
#print(result2)



['क', 'ka\tका', 'kaa\tकि', 'ki\tकी', 'kee\tकु', 'ku\tकू', 'koo\tके', 'ke\tकै', 'kai\tको', 'ko\tकौ', 'kau\tकं', 'kam\tकः', 'kah', 'ख', 'kha\tखा', 'khaa\tखि', 'khi\tखी', 'khee\tखु', 'khu\tखू', 'khoo\tखे', 'khe\tखै', 'khai\tखो', 'kho\tखौ', 'khau\tखं', 'kham\tखः', 'khah', 'ग', 'ga\tगा', 'gaa\tगि', 'gi\tगी', 'gee\tगु', 'gu\tगू', 'goo\tगे', 'ge\tगै', 'gai\tगो', 'go\tगौ', 'gau\tगं', 'gam\tगः', 'gah', 'घ', 'gha\tघा', 'ghaa\tघि', 'ghi\tघी', 'ghee\tघु', 'ghu\tघू', 'ghoo\tघे', 'ghe\tघै', 'ghai\tघो', 'gho\tघौ', 'ghau\tघं', 'gham\tघः', 'ghah', 'च', 'cha\tचा', 'chaa\tचि', 'chi\tची', 'chee\tचु', 'chu\tचू', 'choo\tचे', 'che\tचै', 'chai\tचो', 'cho\tचौ', 'chau\tचं', 'cham\tचः', 'chah', 'छ', 'chha\tछा', 'chhaa\tछि', 'chhi\tछी', 'chhee\tछु', 'chhu\tछू', 'chhoo\tछे', 'chhe\tछै', 'chhai\tछो', 'chho\tछौ', 'chhou\tछं', 'chham\tछः', 'chhah', 'ज', 'ja\tजा', 'jaa\tजि', 'ji\tजी', 'jee\tजु', 'ju\tजू', 'joo\tजे', 'je\tजै', 'jai\tजो', 'jo\tजौ', 'jau\tजं', 'jam\tजः', 'jah', 'झ', 'jha\tझा', 'jhaa\tझि', 'jhi\tझी', 'jhe

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


In [7]:
def removeAl(name):
  df3 = pd.read_csv(name)
  pos = []
  with open(name) as file_obj3:
    reader = csv.reader(file_obj3)
    for row in reader:
      for words in row:
        pos.append(words)
  #print(pos)
  nltk.download('words')
  words = set(nltk.corpus.words.words())
  sente = " ".join(w for w in pos if not w.isalpha())
  result = word_tokenize(sente)
  #print(result)
  sente2 = " ".join(w for w in result if not w.isalpha())
  result2 = word_tokenize(sente2)
  #print(result2)
  return result2
posres = removeAl("positive.csv")
print(len(posres))
negres = removeAl("negative.csv")
print(len(negres))



[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


327
199


In [8]:
newPos = posres[225: ]
newNeg = negres[ :99]
for ele in newNeg:
  print(ele)

प्रतिकूल
रागावला
त्रास
देणे
व्याकुळ
उदासीनता
भयावह
अहंकारी
अत्याचारी
भयानक
वाईट
’
काटेरी
भांडखोर
आक्रोश
खाली
कंटाळवाणा
तुटलेली
कर्कश
बेफिकीर
अनाड़ी
खडबडीत
संकुचित
करा
गोंधळले
विरोधाभास
संक्षारक
भ्रष्ट
वेडा
भितीदायक
गुन्हेगार
क्रूर
रडणे
कटिंग
नुकसान
मृत
क्षय
होत
आहे
विकृत
नकार
द्या
शोचनीय
उदासीन
वंचित
निंदनीय
गलिच्छ
आजार
तिरस्कार
अप्रामाणिक
अपमानास्पद
त्रास
भितीदायक
दुष्ट
अपयशी
सदोष
भीती
क्षीण
लढा
घाणेरडे
फाऊल
’
भयंकर
लोभ
वाकुल्या
दाखवणे
स्थूल
भीषण
अपराधी
हागाडा
कठिण
हानीकारक
द्वेष
घृणास्पद
घरगुती
भयानक
भयानक
विरोधी
दुखावणारा
अज्ञानी
दुर्लक्ष
करा
अपरिपक्व
अपूर्ण
अशक्य
अशोभनीय
इजा
वेडे
कपटी
मत्सर
जंकी
हरले
अतिशय
घाणेरडा
ढेकूण
दुर्भावनापूर्ण
मीन
गोंधळलेला
गहाळ


In [9]:

dicti2 = {
    "प्रतिकूल": -0.4,
    "रागावला": -0.5666,
    "त्रास": -0.78,
    "व्याकुळ": -0.888,
    "उदासीनता": -0.899,
    "भयावह": -0.7999,
    "अहंकारी": -0.899,
    "अत्याचारी": -1,
    "भयानक": -0.9,
    "वाईट": -0.8,
    "काटेरी": -0.67,
    "भांडखोर": -0.877,
    "आक्रोश": -0.845,
    "खाली": -0.45,
    "कंटाळवाणा": -0.78,
    "तुटलेली": -0.34,
    "कर्कश": -0.234,
    "बेफिकीर": -0.65,
    "अनाड़ी": -0.78,
    "खडबडीत": -0.13,
    "संकुचित": -0.67,
    "गोंधळले": -0.77,
    "विरोधाभास": -0.56,
    "संक्षारक": -0.45,
    "भ्रष्ट": -0.7,
    "वेडा": -0.5,
    "भितीदायक": -0.87,
    "गुन्हेगार": -0.77,
    "क्रूर": -0.9,
    "रडणे": -0.5,
    "कटिंग": -0.4,
    "नुकसान": -0.88,
    "मृत": -0.89,
    "क्षय": -0.6,
    "विकृत": -0.5,
    "नकार": -0.66,
    "शोचनीय": -0.5,
    "उदासीन": -0.777,
    "वंचित": -0.877,
    "निंदनीय": -0.99,
    "गलिच्छ": -0.98,
    "आजार": -0.90,
    "तिरस्कार": -0.899,
    "अप्रामाणिक": -1,
    "अपमानास्पद": -1,
    "त्रास": -0.89,
    "भितीदायक": -0.88,
    "दुष्ट": -0.99,
    "अपयशी": -0.5,
    "सदोष": -0.77,
    "भीती": -0.88,
    "क्षीण": -0.89,
    "लढा": -0.5,
    "घाणेरडे": -0.77,
    "फाऊल": -0.77,
    "भयंकर": -0.67,
    "लोभ": -1,
    "वाकुल्या": -0.7,
    "स्थूल": -0.6,
    "भीषण": -0.9,
    "अपराधी": -0.777,
    "हागाडा": -0.4,
    "कठिण": -0.78,
    "हानीकारक": 0.788,
    "घृणास्पद": -0.89,
    "घरगुती": -0.3,
    "भयानक": -0.77,
    "विरोधी": -0.5,
    "दुखावणारा": -0.655,
    "अज्ञानी": -0.89,
    "दुर्लक्ष": -0.77,
    "अपरिपक्व": -0.5,
    "अपूर्ण": -0.77,
    "अशक्य": -0.5,
    "अशोभनीय": -0.67,
    "इजा": -0.66,
    "वेडे": -0.5,
    "कपटी": -0.99,
    "मत्सर": -0.88,
    "जंकी": -0.5,
    "हरले": -0.5,
    "अतिशय": -0.2,
    "घाणेरडा": -0.66,
    "ढेकूण": -0.5,
    "दुर्भावनापूर्ण": -0.4,
    "मीन": -0.3,
    "गोंधळलेला": -0.66,
    "गहाळ": -0.67,
    "नीच": -0.8999,
}


In [10]:
newPos = posres[225: ]
newNeg = negres[99: ]
dictionary = {
    "प्रतिकूल": -0.4,
    "रागावला": -0.5666,
    "त्रास": -0.78,
    "व्याकुळ": -0.888,
    "उदासीनता": -0.899,
    "भयावह": -0.7999,
    "अहंकारी": -0.899,
    "अत्याचारी": -1,
    "भयानक": -0.9,
    "वाईट": -0.8,
    "काटेरी": -0.67,
    "भांडखोर": -0.877,
    "आक्रोश": -0.845,
    "खाली": -0.45,
    "कंटाळवाणा": -0.78,
    "तुटलेली": -0.34,
    "कर्कश": -0.234,
    "बेफिकीर": -0.65,
    "अनाड़ी": -0.78,
    "खडबडीत": -0.13,
    "संकुचित": -0.67,
    "गोंधळले": -0.77,
    "विरोधाभास": -0.56,
    "संक्षारक": -0.45,
    "भ्रष्ट": -0.7,
    "वेडा": -0.5,
    "भितीदायक": -0.87,
    "गुन्हेगार": -0.77,
    "क्रूर": -0.9,
    "रडणे": -0.5,
    "कटिंग": -0.4,
    "नुकसान": -0.88,
    "मृत": -0.89,
    "क्षय": -0.6,
    "विकृत": -0.5,
    "नकार": -0.66,
    "शोचनीय": -0.5,
    "उदासीन": -0.777,
    "वंचित": -0.877,
    "निंदनीय": -0.99,
    "गलिच्छ": -0.98,
    "आजार": -0.90,
    "तिरस्कार": -0.899,
    "अप्रामाणिक": -1,
    "अपमानास्पद": -1,
    "त्रास": -0.89,
    "भितीदायक": -0.88,
    "दुष्ट": -0.99,
    "अपयशी": -0.5,
    "सदोष": -0.77,
    "भीती": -0.88,
    "क्षीण": -0.89,
    "लढा": -0.5,
    "घाणेरडे": -0.77,
    "फाऊल": -0.77,
    "भयंकर": -0.67,
    "लोभ": -1,
    "वाकुल्या": -0.7,
    "स्थूल": -0.6,
    "भीषण": -0.9,
    "अपराधी": -0.777,
    "हागाडा": -0.4,
    "कठिण": -0.78,
    "हानीकारक": 0.788,
    "घृणास्पद": -0.89,
    "घरगुती": -0.3,
    "भयानक": -0.77,
    "विरोधी": -0.5,
    "दुखावणारा": -0.655,
    "अज्ञानी": -0.89,
    "दुर्लक्ष": -0.77,
    "अपरिपक्व": -0.5,
    "अपूर्ण": -0.77,
    "अशक्य": -0.5,
    "अशोभनीय": -0.67,
    "इजा": -0.66,
    "वेडे": -0.5,
    "कपटी": -0.99,
    "मत्सर": -0.88,
    "जंकी": -0.5,
    "हरले": -0.5,
    "अतिशय": -0.2,
    "घाणेरडा": -0.66,
    "ढेकूण": -0.5,
    "दुर्भावनापूर्ण": -0.4,
    "मीन": -0.3,
    "गोंधळलेला": -0.66,
    "गहाळ": -0.67,
    "नीच": -0.8999,
}

dicti = {
    "करा": 0,
    "पुनरुज्जीवित": 0.1,
    "श्रीमंत": 0.5,
    "प्रणय": 0.4,
    "पवित्र": 0.8,
    "सुरक्षितता": 0.7,
    "समाधानी": 0.8,
    "सुरक्षित": 0.6,
    "सुरक्षा": 0.55,
    "समजूतदार": 0.788,
    "सेवा": 0.67,
    "मादक": 0.2,
    "शेअरिंग": 0.899,
    "निवारा": 0.678,
    "चमकणे": 0.78,
    "साधेपणा": 0.9,
    "कौशल्य": 0.888,
    "झोप": 0.5,
    "स्मार्ट": 0.766,
    "स्मॅशिंग": 0.666,
    "हसा": 1,
    "गुळगुळीत": 0.455,
    "आत्मा": 0.3,
    "सोलमेट": 0.888,
    "जागा": 0.4,
    "ठिणगी": 0,
    "विशेष": 0.4,
    "स्थिरता": 0.6,
    "सुरू": 0.5,
    "अजूनही": 0,
    "उत्तेजना": 0.66,
    "ताकद": 0.7,
    "मजबूत": 0.88,
    "अभ्यास": 0.9,
    "जबरदस्त": 1,
    "शैली": 0.66,
    "रसाळ": 0.8,
    "पुरेसा": 0.6,
    "उत्कृष्ट": 0.99,
    "श्रेष्ठ": 0.9,
    "सपोर्ट": 0.77,
    "आश्चर्य": 0.4,
    "वाटले": 0,
    "टिकवणे": 0,
    "गोड": 0.99,
    "प्रतिभावान": 0.888,
    "शिकवा": 0.88,
    "संघ": 0.77,
    "धन्यवाद": 0.88,
    "थरारक": 0.77,
    "भरभराट": 0.8888,
    "सहिष्णुता": 0.9,
    "स्पर्श": 0.66,
    "परंपरा": 0.788,
    "परिवर्तन": 0.8,
    "पारदर्शक": 0.6,
    "भरवसा": 0.999,
    "सत्य": 0.899,
    "अविश्वसनीय": 0.678,
    "बिनशर्त": 0.67,
    "समजून": 0.78,
    "अद्वितीय": 0.89,
    "ऐक्य": 1,
    "उपयुक्त": 0.8,
    "वैध": 0.77,
    "मौल्यवान": 0.88,
    "विविधता": 0.89,
    "अष्टपैलू": 0.7,
    "खूप": 0.7,
    "विजय": 1,
    "जोमदार": 0.8,
    "पुण्यवान": 0.999,
    "शब्दसंग्रह": 0.4,
    "उबदार": 0.89,
    "पाणी": 0.5,
    "संपत्ती": 0.8,
    "स्वागत": 0.89,
    "आहे": 0,
    "कल्याण": 0.89,
    "संपूर्ण": 0.45,
    "इच्छुक": 0.78,
    "जिंकणे": 1,
    "शहाणपण": 1,
    "ज्ञानी": 1,
    "जिंकले": 0.99,
    "अप्रतिम": 1,
    "वर्थ": 0,
    "तरुण": 0.888
}
newDic = {}
posCnt = 0.0
negCnt = 0.0
cntOfWords = 0
negCount=0
for ele in res:
  if ele in newPos:
    cntOfWords = cntOfWords + 1
    score = dicti.get(ele)
    if score is None:
      continue
    else:
      posCnt = posCnt + score
      newDic[ele] = score
  if ele in newNeg:
    negCount = negCount+1
    cntOfWords = cntOfWords + 1
    score2 = dictionary.get(ele)
    if score2 is None:
      continue
    else:
      negCnt = negCnt + score2
      newDic[ele] = score2
Totalcnt = posCnt + negCnt
print(posCnt)
print(negCnt)
print("Final score", Totalcnt)
result = Totalcnt/cntOfWords
print("Result", result)
print(negCount)
print(newDic)

66.796
-2.64
Final score 64.156
Result 0.29840000000000005
69
{'धन्यवाद': 0.88, 'स्वागत': 0.89, 'जागा': 0.4, 'विजय': 1, 'पाणी': 0.5, 'नकार': -0.66, 'अजूनही': 0, 'तरुण': 0.888, 'श्रीमंत': 0.5, 'करा': 0, 'जबरदस्त': 1, 'कल्याण': 0.89, 'जिंकले': 0.99, 'संघ': 0.77, 'परिवर्तन': 0.8, 'गोड': 0.99, 'स्मार्ट': 0.766, 'खूप': 0.7, 'संपूर्ण': 0.45, 'सेवा': 0.67, 'अभ्यास': 0.9, 'सुरक्षा': 0.55, 'मजबूत': 0.88, 'विशेष': 0.4, 'सुरक्षित': 0.6, 'आहे': 0, 'साधेपणा': 0.9, 'पारदर्शक': 0.6, 'सुरू': 0.5}


In [11]:
dictKeys = list(newDic.keys())
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfVectorizer(max_features=200, min_df=1, max_df=0.10)  
x = tfidfconverter.fit_transform(dictKeys).toarray()
dictVal = list(newDic.values())
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, dictVal, 
                                       test_size = 0.5, random_state=24)


In [13]:
print("X_train", X_train)
print("X test", X_test)
print("y train", y_train)
print("y test", y_test)

X_train [[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.70710678 0.         0.70710678]
 [0.         1.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.    

In [14]:
from sklearn.neighbors import  KNeighborsClassifier
from sklearn import preprocessing
lab_enc = preprocessing.LabelEncoder()
y_train = lab_enc.fit_transform(y_train)

knn = KNeighborsClassifier(n_neighbors=10, metric='euclidean')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.tree import DecisionTreeClassifier
# Make a decision tree and train
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
y_pred = tree.predict(X_test)
print("y pred", y_pred)
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
accuracy_dt = accuracy_score(y_test, y_pred)*100
print('Decision Tree:', accuracy_dt)

y pred [0 0 0 0 0 0 0 0 0 7 0 0 0 0 0]


ValueError: ignored

In [15]:
from sklearn.naive_bayes import  GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [16]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
accuracy_gb = accuracy_score(y_test, y_pred)*100
print('GaussianNB Accuracy:',accuracy_gb)

ValueError: ignored

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
#Vectorizing the text data
ctmTr = cv.fit_transform(X_train)
X_test_dtm = cv.fit_transform(X_test)

In [19]:
print(ctmTr.toarray())

[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn import metrics
from sklearn.metrics import accuracy_score
lab_enc = preprocessing.LabelEncoder()
#Training the model
lr = LogisticRegression()
encoded = lab_enc.fit_transform(y_train)
lr.fit(ctmTr, encoded)
lr_score = lr.score(X_test_dtm, y_test)
print("Results for Logistic Regression with CountVectorizer")
print(lr_score)

ValueError: ignored

In [33]:
y_pred_lr = lr.predict(X_test_dtm)
from sklearn.metrics import confusion_matrix
cm_lr = confusion_matrix(y_test, y_pred_lr)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_lr).ravel()
print(tn, fp, fn, tp)
tpr_lr = round(tp/(tp + fn), 4)
tnr_lr = round(tn/(tn+fp), 4)
print(tpr_lr, tnr_lr)

ValueError: ignored

In [41]:
import numpy as np
arr = np.array(X_test)
arr2 = np.array(y_test)
arr.reshape(-1, 1)
arr2.reshape(-1, 1)
lr_score = lr.score(arr, arr2)
print("Results for Logistic Regression with CountVectorizer")
print(lr_score)

NotFittedError: ignored

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dictKeys, dictVal, 
                                        test_size = 0.5, random_state=55)

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
vectorizer = TfidfVectorizer(min_df=1)
vectorizer.fit(X_train)
X_train_vec = vectorizer.transform(X_train)
X_test_vec = vectorizer.transform(X_test)
 

In [39]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn import svm, datasets
#svcl = svm.SVC(kernel = 'rbf')
#parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
#grid_search = GridSearchCV(svm.SVC(kernel = 'poly', gamma='scale'), param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')}, cv = nfolds)
iris = datasets.load_iris()
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(iris.data, iris.target)
GridSearchCV(estimator=svc, param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')})
lr = LogisticRegression()
encoded = lab_enc.fit_transform(y_train)
svc.fit(X_train_vec, encoded)
#predictions = lr.predict(X_test_vec)
#print('AUC: ', roc_auc_score(y_test, predictions))


SVC()

In [40]:
print(X_test_vec)
print(y_test)
svcl_score = svc.score(X_test_vec, y_test)

  (9, 1)	1.0
[0.5, 0, 1, 0.9, 0.67, -0.66, 0.77, 0.88, 0.45, 0.99, 0.5, 0, 0.888, 0.8, 0]


ValueError: ignored